### ISSUE TITLE
Code locator bug

### ISSUE THREAD

**Issue by matiasherranz** [ninja-ide/ninja-ide-web#14]
Press cmd + k, I see nothing in the popup

That's what I see in the console:

[matias@MacBookPro]:ninja-ide (git: master) $ python ninja-ide.py
INFO:ninja_ide.gui.dialogs.wizard_new_project:loaded
DEBUG:ninja_ide.gui.explorer.tree_projects_widget:Ading '/Users/matias/Dev/5Q/ROH' to watcher
DEBUG:ninja_ide.gui.explorer.tree_projects_widget:Ading '/Volumes/Archivos/Dropbox/Cuentas/Logs' to watcher
Traceback (most recent call last):
  File "/Users/matias/Dev/NinjaIDE/GitNinjaIDE_Clone2/ninja-ide/ninja_ide/tools/locator.py", line 161, in run
    self.execute()
  File "/Users/matias/Dev/NinjaIDE/GitNinjaIDE_Clone2/ninja-ide/ninja_ide/tools/locator.py", line 185, in locate_code
    self.__locate_code_in_project(queue_folders, extensions)
  File "/Users/matias/Dev/NinjaIDE/GitNinjaIDE_Clone2/ninja-ide/ninja_ide/tools/locator.py", line 210, in __locate_code_in_project
    one_file.fileName())
  File "/Users/matias/Dev/NinjaIDE/GitNinjaIDE_Clone2/ninja-ide/ninja_ide/tools/locator.py", line 298, in _grep_file_locate
    symbols = symbols_handler.obtain_symbols(content)
  File "/Users/matias/Dev/NinjaIDE/GitNinjaIDE_Clone2/ninja-ide/ninja_ide/tools/introspection.py", line 139, in obtain_symbols
    result = _parse_class(symbol, with_docstrings)
  File "/Users/matias/Dev/NinjaIDE/GitNinjaIDE_Clone2/ninja-ide/ninja_ide/tools/introspection.py", line 43, in _parse_class
    analyzer.expand_attribute(base) for base in symbol.bases])
  File "/Users/matias/Dev/NinjaIDE/GitNinjaIDE_Clone2/ninja-ide/ninja_ide/tools/completion/analyzer.py", line 22, in expand_attribute
    name = attribute.id if name == '' else ("%s.%s" % (attribute.id, name))
AttributeError: 'Call' object has no attribute 'id'

**Comment by matiasherranz** [comment]
I created this ticket wrongly here, it goes here: https://github.com/ninja-ide/ninja-ide/issues/468
