### ISSUE TITLE
Live site bug

### ISSUE THREAD

**Issue by matiasherranz** [ninja-ide/ninja-ide-web#16]
Traceback (most recent call last):

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/core/handlers/base.py", line 111, in get_response
   response = callback(request, _callback_args, *_callback_kwargs)

 File "/home/ninjaide/webapps/ninja_django/ninja_web/plugins/views.py", line 138, in get_plugin
   return render_response(request, 'plugin-detail.html', context)

 File "/home/ninjaide/webapps/ninja_django/ninja_web/common/utils.py", line 9, in render_response
   return render_to_response(_args, *_kwargs)

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/shortcuts/**init**.py", line 20, in render_to_response
   return HttpResponse(loader.render_to_string(_args, *_kwargs), **httpresponse_kwargs)

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/template/loader.py", line 188, in render_to_string
   return t.render(context_instance)

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/template/base.py", line 123, in render
   return self._render(context)

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/template/base.py", line 117, in _render
   return self.nodelist.render(context)

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/template/base.py", line 744, in render
   bits.append(self.render_node(node, context))

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/template/base.py", line 757, in render_node
   return node.render(context)

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/template/loader_tags.py", line 127, in render
   return compiled_parent._render(context)

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/template/base.py", line 117, in _render
   return self.nodelist.render(context)

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/template/base.py", line 744, in render
   bits.append(self.render_node(node, context))

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/template/base.py", line 757, in render_node
   return node.render(context)

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/template/loader_tags.py", line 64, in render
   result = block.nodelist.render(context)

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/template/base.py", line 744, in render
   bits.append(self.render_node(node, context))

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/template/base.py", line 757, in render_node
   return node.render(context)

 File "/home/ninjaide/webapps/ninja_django/lib/python2.6/django/template/defaulttags.py", line 450, in render
   raise e

NoReverseMatch: Reverse for 'user_detail' with arguments '('',)' and keyword arguments '{}' not found.

**Comment by pmourelle** [comment]
I'm closing this issue because is not valid any more. Now we have ANOTHER user profile app giving its own issues :P
