### ISSUE TITLE
Fail to execute the site

### ISSUE THREAD

**Issue by diegosarmentero** [ninja-ide/ninja-ide-web#42]
./manage.py createdb is not recognized, and using syncdb throws the following traceback:

./manage.py syncdb
Traceback (most recent call last):
  File "./manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/gatox/.virtualenvs/ninjaweb/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/gatox/.virtualenvs/ninjaweb/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gatox/.virtualenvs/ninjaweb/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/home/gatox/.virtualenvs/ninjaweb/local/lib/python2.7/site-packages/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/home/gatox/.virtualenvs/ninjaweb/local/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/home/gatox/.virtualenvs/ninjaweb/local/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/home/gatox/.virtualenvs/ninjaweb/local/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/home/gatox/.virtualenvs/ninjaweb/local/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/home/gatox/.virtualenvs/ninjaweb/local/lib/python2.7/site-packages/django/db/models/loading.py", line 97, in load_app
    app_module = import_module(app_name)
  File "/home/gatox/.virtualenvs/ninjaweb/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named compressor

**Comment by pmourelle** [comment]
This error was raised due to old mezzanine version that used old PIL module instead of its new version: pillow.
This should not happen any more. Please revise and close/comment this issue.
